apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: stateless   # ✅ namespace goes here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.21  # <-- for rollback test change this to 'nginx:broken'
          ports:
            - containerPort: 80
