apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: stateless
  labels:
    app: nginx
spec:
  selector:
    app: nginx-app    # ✅ matches Deployment pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
